#! /bin/sh
if [ $JAVA_HOME == '/System/Library/Frameworks/JavaVM.framework/Versions/1.5.0/Home' ] 
then
JAVA_LIB_CLASSES=classes_x86_32
else
JAVA_LIB_CLASSES=classes
fi
SOLVERDIR=../lib/solver
../bin/jlc -assert -ext pbnj -cp $JAVA_LIB_CLASSES:$SOLVERDIR/kodkod/jar/kodkod.jar $1.pbj
java -ea -cp .:$JAVA_LIB_CLASSES:../classes:$SOLVERDIR/kodkod/jar/kodkod.jar:$SOLVERDIR/kodkod/jar/org.sat4j.core.jar -Djava.library.path=$SOLVERDIR/x86-mac $1
