all: ;\
    javac -cp examples/classes -d examples/classes examples/classes/pbnj/util/Iterator.java;\
    javac -cp examples/classes -d examples/classes examples/classes/pbnj/util/Collection.java;\
    javac -cp examples/classes -d examples/classes examples/classes/pbnj/util/AbstractCollection.java;\
    javac -cp examples/classes -d examples/classes examples/classes/pbnj/util/AbstractList.java;\
    javac -cp examples/classes -d examples/classes examples/classes/pbnj/util/Enumeration.java;\
    examples/pbnjc examples/classes/pbnj/awt/Point.pbj -d examples/classes;\
    examples/pbnjc examples/classes/pbnj/util/ArrayList.pbj -d examples/classes;\
    javac -cp examples/classes -d examples/classes examples/classes/pbnj/util/Collections.java;\
    examples/pbnjc examples/classes/pbnj/util/Vector.pbj -d examples/classes;\
    examples/pbnjc examples/classes/pbnj/examples/primitives/PBJString.pbj -d examples/classes/;\
    examples/pbnjc examples/classes/pbnj/examples/primitives/PBJInteger.pbj -d examples/classes/;\
    examples/pbnjc examples/classes/pbnj/examples/primitives/PBJFloat.pbj -d examples/classes/;\
    examples/pbnjc examples/classes/pbnj/examples/primitives/PBJLong.pbj -d examples/classes/;\
    examples/pbnjc examples/classes/pbnj/examples/primitives/PBJDouble.pbj -d examples/classes/;\
    examples/pbnjc examples/classes/pbnj/examples/primitives/PBJMap.pbj -d examples/classes/;\
    examples/pbnjc examples/classes/pbnj/examples/primitives/PBJSet.pbj -d examples/classes/;\
    examples/pbnjc examples/classes/pbnj/examples/primitives/PBJUtils.pbj -d examples/classes/;\
 
