#! /bin/sh
JAVA_LIB_CLASSES=classes
SOLVERDIR=../../../lib/solver
java -ea -cp ../..:.:../../$JAVA_LIB_CLASSES:../../../classes:$SOLVERDIR/kodkod/jar/kodkod.jar:../../../../../../tools/antlr/jar/antlr-3.1.3.jar:. -Djava.library.path=$SOLVERDIR/x86-mac $1 $2 
