#! /bin/sh
JAVA_LIB_CLASSES=classes
SOLVERDIR=../../../lib/solver
../../../bin/jlc -assert -ext pbnj -cp ../..:../../$JAVA_LIB_CLASSES:$SOLVERDIR/kodkod/jar/kodkod.jar:../../../../../../tools/antlr/jar/antlr-3.1.3.jar:. $1 $2 
